#ifndef HJ_LEARN_CAFFE_TOOLS_CONFIGS
#define HJ_LEARN_CAFFE_TOOLS_CONFIGS

//使用下面的宏选择阅读与调试的tools
//#define TOOLS_CAFFE_CPP
//#define TOOLS_CONVERT_IMAGESET_CPP
//#define TOOLS_EXTRACT_FEATURES_CPP
//#define TOOLS_FASTER_RCNN_CPP
//#define TOOLS_FORWORD_CIFAR10_CPP
//#define TOOLS_FORWORD_LENET_CPP
//#define TOOLS_TEST_CAFFE_CLASSIFIER_CPP
#define TOOLS_TEST_NET_CPP
//#define TOOLS_TEST_YOLO_CPP

#endif // !HJ_LEARN_CAFFE_TOOLS_CONFIGS
